wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1678164412.920664
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.13.10
      8:
      - 5
architecture:
  desc: null
  value: Mobilenetv2
batches:
  desc: null
  value: 391
dataset:
  desc: null
  value: Cifar100
epochs:
  desc: null
  value: 200
